os: linux
dist: focal
language: cpp
compiler: gcc

addons:
  apt:
    update: true

before_install:
  - scripts/deps.sh

script:
  - scripts/build.sh
  - cd build
  - make docs
  - make test

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: main
  local_dir: documentation
  repo: stephgalibert/SFGE
